/* Hiding pages. Every item maps to a key in /data/adb/nextsusfs/config.sh that the boot
   scripts read, so a switch here changes what really happens at the next boot.
   type: 'toggle' (0/1), 'text' (quoted string, validated by `pattern`). */

export const PAGES = [
  {
    id: 'paths', icon: 'paths',
    t: { en: 'Paths & files', ar: 'المسارات والملفات' },
    d: { en: 'Folders and files that give root away', ar: 'مجلدات وملفات تكشف الروت' },
    items: [
      { key: 'config_hide_custom_recovery',
        en: ['Hide custom recovery folders', 'TWRP and OrangeFox folders, /data/recovery and install-recovery.sh.'],
        ar: ['إخفاء مجلدات الريكفري', 'مجلدات TWRP و OrangeFox و ‎/data/recovery وملف install-recovery.sh.'] },
      { key: 'config_paths_hiding__non_standard_sdcard',
        en: ['Hide unusual folders in storage', 'Any folder in internal storage that stock Android does not create. Download, DCIM and the other standard folders stay visible.'],
        ar: ['إخفاء المجلدات الغريبة في الذاكرة', 'أي مجلد في الذاكرة الداخلية ما ينشئه أندرويد الأصلي. تبقى Download و DCIM وباقي المجلدات القياسية ظاهرة.'] },
      { key: 'config_paths_hiding__non_standard_sdcard_android',
        en: ['Hide unusual folders in Android/', 'Anything in storage/Android besides data, media and obb.'],
        ar: ['إخفاء المجلدات الغريبة في Android/', 'أي شيء داخل مجلد Android غير data و media و obb.'] },
      { key: 'config_paths_hiding__data_local_tmp',
        en: ['Hide files in /data/local/tmp', 'ADB tools and root scripts usually leave files here.'],
        ar: ['إخفاء ملفات ‎/data/local/tmp', 'أدوات ADB وسكربتات الروت تترك ملفاتها هنا عادةً.'] },
      { key: 'config_fix_data_local_tmp_inconsistencies',
        en: ['Fix /data/local/tmp permissions', 'Restores the stock owner, mode and SELinux label, and shows apps stock file stats.'],
        ar: ['إصلاح صلاحيات ‎/data/local/tmp', 'يرجّع المالك والصلاحيات وتسمية SELinux للأصل، ويعرض للتطبيقات بيانات ملف أصلية.'] },
      { key: 'config_hide_addon_d',
        en: ['Hide /system/addon.d', 'Survival scripts left by custom ROMs and GApps.'],
        ar: ['إخفاء ‎/system/addon.d', 'سكربتات تتركها الرومات المخصصة و GApps.'] },
      { key: 'config_spoof_hosts',
        en: ['Spoof the hosts file', 'Makes /system/etc/hosts look unmodified. Useful with ad-block modules.'],
        ar: ['تزييف ملف hosts', 'يخلي ‎/system/etc/hosts يبان غير معدّل. مفيد مع وحدات حجب الإعلانات.'] },
      { key: 'config_hide_all_zygisk_libs',
        en: ['Hide all Zygisk libraries', 'Removes every module\'s Zygisk library from apps\' memory maps, not only the NEXT stack.'],
        ar: ['إخفاء كل مكتبات Zygisk', 'يشيل مكتبة Zygisk لكل وحدة من خرائط ذاكرة التطبيقات، مو بس منظومة NEXT.'] },
      { key: 'config_hide_backup_folder',
        en: ['Hide the backup folder', 'Hides Download/NextSUSFS from apps. Root file managers still see it.'],
        ar: ['إخفاء مجلد النسخة الاحتياطية', 'يخفي Download/NextSUSFS عن التطبيقات. مدراء الملفات اللي عندها روت تشوفه.'] },
      { key: 'config_hide_data_adb',
        en: ['Hide /data/adb completely', 'Stock Android has no /data/adb, so apps that find it know the device is rooted.', 'Experimental. Turn off if a module stops working.'],
        ar: ['إخفاء ‎/data/adb بالكامل', 'أندرويد الأصلي ما فيه ‎/data/adb، فالتطبيق اللي يلقاه يعرف إن الجهاز مروّت.', 'تجريبي. أطفه إذا وحدة توقفت عن العمل.'] },
      { key: 'config_hide_suspicious_pty',
        en: ['Hide terminal sessions', 'Hides /dev/pts 0–5 opened by root shells.', 'May break terminal apps.'],
        ar: ['إخفاء جلسات الطرفية', 'يخفي ‎/dev/pts من 0 إلى 5 اللي تفتحها أوامر الروت.', 'قد يعطّل تطبيقات الطرفية.'] },
      { key: 'config_hide_framework_res_apk',
        en: ['Hide framework-res.apk from maps', 'Removes it from apps\' memory maps. Only needed against a few detectors.'],
        ar: ['إخفاء framework-res.apk من الذاكرة', 'يشيله من خرائط ذاكرة التطبيقات. تحتاجه ضد كاشفات قليلة فقط.'] },
    ],
  },
  {
    id: 'rom', icon: 'rom',
    t: { en: 'Custom ROM', ar: 'الروم المخصص' },
    d: { en: 'Traces of LineageOS, crDroid and others', ar: 'آثار LineageOS و crDroid وغيرها' },
    items: [
      { key: 'config_hide_custom_rom_paths',
        en: ['Hide custom ROM files', 'Finds files named after known ROMs in the system partitions and /data, and hides them.'],
        ar: ['إخفاء ملفات الروم المخصص', 'يدوّر على ملفات تحمل أسماء رومات معروفة في أقسام النظام و ‎/data ويخفيها.'] },
      { key: 'config_hide_custom_rom_paths_2',
        en: ['Extreme ROM file hiding', 'Also searches /data/misc, dalvik-cache and resource-cache.', 'Makes boot slower.'],
        ar: ['إخفاء ملفات الروم (شامل)', 'يدوّر كمان في ‎/data/misc و dalvik-cache و resource-cache.', 'يبطّئ الإقلاع.'] },
      { key: 'config_hide_lineage_strings',
        en: ['Hide LineageOS strings', 'Shows apps empty copies of sepolicy, file_contexts and .rc files that mention Lineage.'],
        ar: ['إخفاء نصوص LineageOS', 'يعرض للتطبيقات نسخ فاضية من ملفات sepolicy و file_contexts و ‎.rc اللي فيها Lineage.'] },
      { key: 'config_rom_props',
        en: ['Remove custom ROM properties', 'Deletes system properties containing ROM names, and ro.modversion.'],
        ar: ['حذف خصائص الروم المخصص', 'يحذف خصائص النظام اللي فيها أسماء رومات، و ro.modversion.'] },
      { key: 'config_spoof_libstagefright',
        en: ['Spoof libstagefright.so', 'Shows apps an empty /system/lib64/libstagefright.so.'],
        ar: ['تزييف libstagefright.so', 'يعرض للتطبيقات ملف ‎/system/lib64/libstagefright.so فاضي.'] },
    ],
  },
  {
    id: 'kernel', icon: 'kernel',
    t: { en: 'Kernel identity', ar: 'هوية النواة' },
    d: { en: 'Kernel name, boot state and logs', ar: 'اسم النواة وحالة الإقلاع والسجلات' },
    items: [
      { key: 'config_spoof_uname',
        en: ['Spoof kernel name', 'Shows a stock-looking kernel name instead of yours, e.g. 6.1.x-android14-….'],
        ar: ['تزييف اسم النواة', 'يعرض اسم نواة يشبه الأصلي بدل اسم نواتك، مثل ‎6.1.x-android14-….'] },
      { key: 'config_custom_spoof_uname',
        en: ['Use my own kernel name', 'Overrides the automatic name with the two values below. Copy them from uname -r and uname -v on a stock ROM.'],
        ar: ['استخدم اسم نواة من عندي', 'يستبدل الاسم التلقائي بالقيمتين تحت. انسخهم من uname -r و uname -v على روم أصلي.'] },
      { key: 'config_custom_uname_kernel_release', type: 'text', dflt: 'default', pattern: /^[A-Za-z0-9._+\-]{1,64}$/,
        en: ['Kernel release', 'Like 6.1.75-android14-11-g1234abcd. "default" keeps the real one.'],
        ar: ['إصدار النواة', 'مثل 6.1.75-android14-11-g1234abcd. كلمة default تخلي الأصلي.'] },
      { key: 'config_custom_uname_kernel_version', type: 'text', dflt: 'default', pattern: /^[A-Za-z0-9._+:#\- ]{1,96}$/,
        en: ['Kernel version', 'Like #1 SMP PREEMPT Mon Jan 1 00:00:00 UTC 2024.'],
        ar: ['نسخة النواة', 'مثل ‎#1 SMP PREEMPT Mon Jan 1 00:00:00 UTC 2024.'] },
      { key: 'config_spoof_cmdline_or_bootconfig',
        en: ['Spoof boot state', 'Shows apps verifiedbootstate=green and warranty_bit=0 in /proc/cmdline or /proc/bootconfig.'],
        ar: ['تزييف حالة الإقلاع', 'يعرض للتطبيقات verifiedbootstate=green و warranty_bit=0 في ‎/proc/cmdline أو ‎/proc/bootconfig.'] },
      { key: 'config_hide_sus_mnts_for_non_su_procs',
        en: ['Hide root mounts from apps', 'Hides suspicious mounts from every non-root process early, before Zygote caches them.'],
        ar: ['إخفاء تركيبات الروت عن التطبيقات', 'يخفي التركيبات المشبوهة عن كل عملية بدون روت من بدري، قبل ما يحفظها Zygote.'] },
      { key: 'config_enable_avc_log_spoofing',
        en: ['Spoof SELinux denial logs', 'Hides the su domain in avc logs, which apps read to detect root.'],
        ar: ['تزييف سجلات رفض SELinux', 'يخفي نطاق su في سجلات avc اللي تقرأها التطبيقات لكشف الروت.'] },
      { key: 'config_enable_log',
        en: ['SuSFS kernel log', 'Writes SuSFS activity to the kernel log. Leave off unless debugging.'],
        ar: ['سجل SuSFS في النواة', 'يكتب نشاط SuSFS في سجل النواة. خلّه مطفي إلا وقت التصحيح.'] },
    ],
  },
  {
    id: 'props', icon: 'props',
    t: { en: 'System properties', ar: 'خصائص النظام' },
    d: { en: 'Bootloader, build and patch values', ar: 'قيم البوتلودر والبناء والتحديث الأمني' },
    items: [
      { key: 'config_spoof_system_properties',
        en: ['Spoof boot & security properties', 'Locked bootloader, green verified boot, user build with release-keys, ADB off.'],
        ar: ['تزييف خصائص الإقلاع والأمان', 'بوتلودر مقفل، إقلاع موثّق أخضر، بناء user بمفاتيح release، و ADB مطفي.'] },
      { key: 'config_spoof_system_properties_repeat',
        en: ['Re-apply every minute', 'For ROMs that reset these properties after boot.'],
        ar: ['إعادة التطبيق كل دقيقة', 'للرومات اللي ترجّع هذي الخصائص بعد الإقلاع.'] },
      { key: 'config_spoof_fingerprint_properties',
        en: ['Clean the build fingerprint', 'Removes userdebug, lineage, crdroid and evolution from every fingerprint.'],
        ar: ['تنظيف بصمة البناء', 'يشيل userdebug و lineage و crdroid و evolution من كل البصمات.'] },
      { key: 'config_spoof_utc_properties',
        en: ['Match build time (UTC)', 'Makes every partition report the same build time. Mismatches reveal a custom ROM.'],
        ar: ['توحيد وقت البناء (UTC)', 'يخلي كل الأقسام تعرض نفس وقت البناء. الاختلاف يكشف الروم المخصص.'] },
      { key: 'config_spoof_date_properties',
        en: ['Match build date', 'Same as above, for the readable build date.'],
        ar: ['توحيد تاريخ البناء', 'نفس اللي فوق، لتاريخ البناء المقروء.'] },
      { key: 'config_spoof_os_security_patch_level_property',
        en: ['Current Android security patch', 'Reports this month\'s patch level.'],
        ar: ['تحديث أمان أندرويد حالي', 'يعرض مستوى تحديث الشهر الحالي.'] },
      { key: 'config_spoof_vendor_security_patch_level_property',
        en: ['Current vendor security patch', 'Same, for the vendor partition.'],
        ar: ['تحديث أمان المصنّع حالي', 'نفسه، لقسم vendor.'] },
      { key: 'config_pif_props',
        en: ['Remove Play Integrity Fix leftovers', 'Deletes pihook, pixelprops and spoof properties.'],
        ar: ['حذف بقايا Play Integrity Fix', 'يحذف خصائص pihook و pixelprops و spoof.'] },
      { key: 'config_spoof_verified_boot_hash', type: 'text', dflt: '', pattern: /^([0-9a-fA-F]{64})?$/,
        en: ['Verified boot hash', 'ro.boot.vbmeta.digest. Paste the 64-character hash from Key Attestation, or leave empty.'],
        ar: ['بصمة الإقلاع الموثّق', 'ro.boot.vbmeta.digest. الصق البصمة (64 حرف) من تطبيق Key Attestation، أو خلّه فاضي.'] },
    ],
  },
  {
    id: 'ksu', icon: 'ksu',
    t: { en: 'KernelSU', ar: 'KernelSU' },
    d: { en: 'Root manager features applied at boot', ar: 'ميزات مدير الروت تُطبَّق عند الإقلاع' },
    items: [
      { key: 'config_kernel_umount',
        en: ['Kernel unmount', 'KernelSU unmounts module files for apps without root.'],
        ar: ['فك التركيب من النواة', 'KernelSU يفك تركيب ملفات الوحدات عن التطبيقات اللي ما عندها روت.'] },
      { key: 'config_selinux_hide',
        en: ['Hide SELinux changes', 'KernelSU hides its SELinux policy changes from apps.'],
        ar: ['إخفاء تعديلات SELinux', 'KernelSU يخفي تعديلاته على سياسة SELinux عن التطبيقات.'] },
      { key: 'config_su_compat',
        en: ['su compatibility', 'The su command for apps you granted root. Off hides su better, but some root apps stop working.'],
        ar: ['توافق su', 'أمر su للتطبيقات اللي عطيتها روت. إطفاؤه يخفي su أكثر، بس بعض تطبيقات الروت تتعطل.'] },
      { key: 'config_selinux',
        en: ['Keep SELinux enforcing', 'Switches SELinux back to Enforcing at boot if something made it permissive.'],
        ar: ['إبقاء SELinux على Enforcing', 'يرجّع SELinux لوضع Enforcing عند الإقلاع إذا شيء حوّله Permissive.'] },
    ],
  },
  {
    id: 'dev', icon: 'dev',
    t: { en: 'Developer & debugging', ar: 'المطوّر والتصحيح' },
    d: { en: 'Switches banking apps check', ar: 'إعدادات تفحصها تطبيقات البنوك' },
    note: { en: 'These are set at every boot: on turns the setting on, off turns it off.', ar: 'هذي تنضبط مع كل إقلاع: التشغيل يفعّل الإعداد، والإطفاء يطفيه.' },
    items: [
      { key: 'config_developer_options',
        en: ['Developer options', 'Most banking apps refuse to run while this is on.'],
        ar: ['خيارات المطوّر', 'أغلب تطبيقات البنوك ترفض تشتغل وهو مفعّل.'] },
      { key: 'config_usb_debugging',
        en: ['USB debugging', 'ADB over cable.'],
        ar: ['تصحيح USB', 'ADB عن طريق الكيبل.'] },
      { key: 'config_wireless_debugging',
        en: ['Wireless debugging', 'ADB over Wi-Fi.'],
        ar: ['التصحيح اللاسلكي', 'ADB عن طريق الواي فاي.'] },
      { key: 'config_disable_child_process_restrictions',
        en: ['Stop the phantom-process killer', 'Android 12+ stops killing background child processes (Termux and similar).'],
        ar: ['إيقاف قاتل العمليات الخلفية', 'أندرويد 12 وأعلى يوقف قتل العمليات الفرعية في الخلفية (Termux وأمثاله).'] },
    ],
  },
  {
    id: 'display', icon: 'display',
    t: { en: 'Display extras', ar: 'إضافات الشاشة' },
    d: { en: 'Small tweaks, not hiding', ar: 'تعديلات بسيطة، مو إخفاء' },
    items: [
      { key: 'config_saturation',
        en: ['Boost colour saturation', 'Doubles SurfaceFlinger saturation.'],
        ar: ['رفع تشبّع الألوان', 'يضاعف تشبّع الألوان في SurfaceFlinger.'] },
      { key: 'config_show_refresh_rate',
        en: ['Show refresh rate', 'Draws the current refresh rate on screen.'],
        ar: ['إظهار معدل التحديث', 'يعرض معدل تحديث الشاشة الحالي فوق الشاشة.'] },
    ],
  },
]

/* The list files the boot script reads line by line (# starts a comment). */
export const LISTS = [
  { file: 'custom_sus_path.txt',
    en: ['Hidden paths', 'Paths hidden once at boot. Use for files that do not change.'],
    ar: ['مسارات مخفية', 'مسارات تنخفي مرة وحدة عند الإقلاع. للملفات اللي ما تتغير.'] },
  { file: 'custom_sus_path_loop.txt',
    en: ['Re-hidden paths', 'Hidden again whenever they are recreated. Use for folders apps write to.'],
    ar: ['مسارات يُعاد إخفاؤها', 'تنخفي من جديد كل ما انعادت إنشاؤها. للمجلدات اللي تكتب فيها التطبيقات.'] },
  { file: 'custom_sus_map.txt',
    en: ['Hidden from memory maps', 'Files removed from /proc/self/maps, such as Zygisk libraries.'],
    ar: ['مخفية من خرائط الذاكرة', 'ملفات تنشال من ‎/proc/self/maps، مثل مكتبات Zygisk.'] },
  { file: 'custom_kernel_umount.txt',
    en: ['Unmounted for apps', 'Mount points KernelSU unmounts for apps without root.'],
    ar: ['فك تركيب للتطبيقات', 'نقاط تركيب يفكها KernelSU عن التطبيقات اللي ما عندها روت.'] },
  // One "<path> <new path> <uid scheme>" per line: opening <path> opens <new path> instead.
  { file: 'custom_open_redirect.txt', kind: 'redirect',
    placeholder: '/system/etc/hosts /data/adb/nextsusfs/hosts 3',
    en: ['Open redirect', 'Opening a path opens another file instead. One line each: path, new path, scope.',
      'Scope:\n0  non-app processes\n1  root processes without su\n2  every process without su\n3  apps without root (recommended)\n4  every unmounted process\nBoth files must exist; set their SELinux context yourself.'],
    ar: ['إعادة توجيه الفتح', 'فتح مسار يفتح ملف ثاني بداله. سطر لكل وحدة: المسار، المسار البديل، النطاق.',
      'النطاق:\n0  العمليات غير التطبيقات\n1  عمليات الروت بدون su\n2  كل العمليات بدون su\n3  التطبيقات بدون روت (المقترح)\n4  كل العمليات المفكوك عنها التركيب\nلازم الملفين يكونون موجودين، وسياق SELinux عليك.'] },
  { file: 'custom_sus_kstat.txt',
    en: ['Spoofed file stats', 'Files whose timestamps are shown to apps as an old, untouched date. Use for system files you edited, so their modified time does not give you away.',
      'One path per line. ino, device and size stay real; only the access/modify/change times are spoofed.'],
    ar: ['تزييف بيانات الملفات', 'ملفات تُعرض أوقاتها للتطبيقات بتاريخ قديم غير معدّل. استخدمها لملفات نظام عدّلتها، عشان وقت التعديل ما يفضحك.',
      'سطر لكل مسار. الـ ino والجهاز والحجم تبقى حقيقية؛ يتزيّف فقط وقت الوصول والتعديل والتغيير.'] },
]
